const players = [
  { name: "CJ Staugler", scores: [54, 49], handicap: null },
  { name: "Donny Sams", scores: [54, 59], handicap: null },
  { name: "Eric Sams", scores: [55, 55], handicap: null },
  { name: "Heath Coate", scores: [55, 55], handicap: null },
  { name: "Gabe Archer", scores: [58, 57], handicap: null },
  { name: "Chad Schmitmeyer", scores: [61, 60], handicap: null },
  { name: "Drew Braun", scores: [62, 57], handicap: null },
  { name: "Chicken", scores: [63, 58], handicap: null },
  { name: "Cory Hathaway", scores: [63, 57], handicap: null },
  { name: "Chip Alig", scores: [65, 75], handicap: null },
  { name: "Brian Monroe", scores: [66, 62], handicap: null },
  { name: "Zach Schlarman", scores: [76, 80], handicap: null },
  { name: "Kyle Trafzer", scores: [77, 69], handicap: null },
  { name: "Adam Hulatt", scores: [60, 55], handicap: null },
  { name: "Nate Giesege", scores: [62, 55], handicap: null },
];
